### ISSUE TITLE
web.html example does not work any more

### ISSUE THREAD

**Issue by kewisch** [kewisch/sepa.js#15]
In a Firefox nightly I tested the web.html demo. When creating xml, it first complains about the xmlns setAttributeNS calls not working due to NamespaceError. This can be solved by not using setAttributeNS but instead setAttribute. Also, for consistency and less confusion we should change the variable name for XSI_NS to XSD_NAMESPACE or something more specific.

Second, it seems that the SEPA types are not set correctly. When instanciating a `SepaDocument` with the default pain type, it will still try to get `SEPATypes[painFormat]`, which is undefined. This could be fixed by changing to `SEPATypes[this._painFormat]`. Even with that change, I am not sure that is the correct way to set the type, because for example with `pain.001.001.02`, the `_type` variable will also be set to `pain.001.001.02`, and hence an xml element `<pain.001.001.02>` will be created. Is that exptected?

@OtaK @acemtp can you take a look?

**Comment by OtaK** [comment]
In pain.001.001.02 and pain.008.001.01 it is expected that the root node is actually respectively <pain.001.001.02> and <pain.008.001.01>. It's how SEPA XML v1 is made. (and it's really bad)

**Comment by enboig** [comment]
Does it work in an HTML file? I just want to make a html to load data from a local CSV file and generate a valid XML file.

**Comment by enboig** [comment]
I tried applying this solutions, but it still complains at sepa.js, and I tried replacing setAttributeNS by setAttribute but the error just change;

sepa.js:126 Uncaught NamespaceError: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/2001/XMLSchema-instance' is an invalid namespace for attributes.toXML @ sepa.js:126toString @ sepa.js:146process @ web.js:38onsubmit @ web.html:31
Navigated to file:///tmp/sepa.js/examples/web.html?


Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'http://www.w3.org/2001/XMLSchema-instance' is not a valid attribute name.toXML @ sepa.js:126toString @ sepa.js:146process @ web.js:38onsubmit @ web.html:31
Navigated to file:///tmp/sepa.js/examples/web.html?

Any hint?

**Comment by lippertto** [comment]
I tried to reproduce this. Currently, the demo does not work because we no longer check in the `sepa.min.js` file into the repository.
I would suggest to just reference `lib/sepa.js` on the current trunk.
What do you think @kewisch ?

After that has been fixed, I can try to reproduce the original problem.

**Comment by lippertto** [comment]
I have created a PR. The changes work locally, but if I reference the sepa.js source code from the html file, I get a problem. I assume that we should need a different method to distribute the javascript file, but I have no experience in that.

In any case, we should update the code to work at least in theory.

**Comment by kewisch** [comment]
Sure, let's change it. IIRC the problem here is mime types. Firefox used to not care if javascript files were served with e.g. text/plain, but Chrome needed it to be application/javascript or similar. This might have changed for Firefox in the meanwhile.
