### ISSUE TITLE
Exception thrown when calling toString() in a browser environement

### ISSUE THREAD

**Issue by vanwalj** [kewisch/sepa.js#16]
Hello,

First, thank you, this module is pretty neat ! 

The only problem is that i can't get it working client side.

The browser DOM Document API throw an error when using `setAttributeNS` on body with `http://www.w3.org/2001/XMLSchema-instance`

```
Error: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/2001/XMLSchema-instance' is an invalid namespace for attributes.
```

Commenting out those 3 lines solve the problem, but then the file is not a valid SEPA file (i guess)
https://github.com/kewisch/sepa.js/blob/master/lib/sepa.js#L126

Any suggestions ? 

Thanks again !

Browser: Google Chrome Version 52.0.2743.116 (64-bit)

**Comment by kewisch** [comment]
I think this is handled differently now, please reopen if this still happens!
