### ISSUE TITLE
False positive while validating IBAN

### ISSUE THREAD

**Issue by dabeck** [kewisch/sepa.js#18]
I've encountered a problem where the `validateIBAN()` function returns a wrong result.

```
validateIBAN("santander") === true
```

**Comment by kewisch** [comment]
I can confirm, interesting behavior. Do you think you could look into why this is happening?

**Comment by dabeck** [comment]
I just investigated the problem and noticed that this is not really a bug but happens due to the simplicity of this library. To overcome this false positive one should do a more precise validation with country specific parameters e.g. IBAN-length for country code and format description. So in general all calculation is correct but not enough to validate an international IBAN.

**Comment by OtaK** [comment]
Already noticed this problem, which is why I added a function to bypass validations when you're sure of your format: `SEPA.enableValidations(false);`

**Comment by kewisch** [comment]
@dabeck do you think you could send a pull request to improve the checks here? I'd appreciate!

**Comment by lippertto** [comment]
Hello @kewisch , I can have a look into this bug. I would include jest as testing library to reproduce the bug and to fix it for good. Is that fine with you?

**Comment by kewisch** [comment]
Yep, that works for me. Glad to see the first few tests on this!
