### ISSUE TITLE
xml Document tag contains errors

### ISSUE THREAD

**Issue by bizarrochris** [kewisch/sepa.js#19]
I'm using the module to create a sepa XML in node js. It works great and I got to an xml really fast.

However the document I get does not validate and also looks different from your example:

```  <Document xmlns="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02" xmlns:xmlns="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02 pain.008.003.02.xsd" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02">```

To my knowledge the correct Tag would be:

```
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02 pain.008.003.02.xsd">
```

Am I missing something or is this a bug that can be fixed inside the module? Thx in advance

**Comment by Snap974** [comment]
Hi, anyone have some informations about this please?

I have the same problem, I want to generate a SEPA XML Direct Debit.

Thanks, have a nice day

**Comment by bizarrochris** [comment]
@Snap974 The solution I found was replacing the wrong string with the right string hardcoded via string.replace()

Also I added: ```  <?xml version="1.0" encoding="UTF-8"?> ``` at the beginning, as some banks do need that

**Comment by kewisch** [comment]
Hey Folks, thanks for bringing this up. If you can fix the bug in the library I am happy to accept the PR. It looks like way too many xmlns are being generated there.

**Comment by bizarrochris** [comment]
@kewisch Hi Philipp, I created a PR for fixing the code. Would be great if you could merge it, and also publish a new version to NPM.
Cheers
