### ISSUE TITLE
Version pain.001.003.03

### ISSUE THREAD

**Issue by stefanve** [kewisch/sepa.js#22]
Currently it seems this only supports pain.001.001.02 which is pretty old. Has someone tried creating the newer versions?

**Comment by stefanve** [comment]
Seems it actually works with `pain.001.003.03` but some validations are different so my test data failed. I close this.

**Comment by kewisch** [comment]
Is there anything that can be changed in sepa.js that would make it more compatible so that this wouldn't have been an issue?
