### ISSUE TITLE
Validating BIC+IBAN

### ISSUE THREAD

**Issue by stefanve** [kewisch/sepa.js#23]
Is there a way to validate the BIC + IBAN combination?
I get "country mismatch in BIC/IBAN" when doing doc.toXML(), but since the error appears after all data is collected I have no way if catching it while I still have information about which data is faulty.

**Comment by kewisch** [comment]
Looking at the assertion, it seems all you need to do is make sure the country code in the IBAN and BIC match:
```javascript
var countryMatches = (this[pullFrom + 'BIC'].length === 0 || this[pullFrom + 'BIC'].substr(4, 2) === this[pullFrom + 'IBAN'].substr(0, 2));
```
