### ISSUE TITLE
Valid BIC fails validation

### ISSUE THREAD

**Issue by pkaske** [kewisch/sepa.js#30]
The BIC DAAEDEDDXX seem to fail validation while it's actually valid?

Can you confirm this problem? The error states: debtorBIC must have any value of: 0 8 11(found: 10)

**Comment by kewisch** [comment]
BIC codes should normally be 8 or 11 characters long. Do you mean `DAAEDEDDXXX` ?

**Comment by pkaske** [comment]
Yeah, you're right. The website that I used to check the BIC autocorrected the last X at the end and I didn't notice... Sorry about that!
