### ISSUE TITLE
Bancs required debtor id

### ISSUE THREAD

**Issue by Sin3W** [kewisch/sepa.js#35]
Good day,

I have been creating SEPA XML with your tool and works fantastic, but some bancs require additional info in the <GrpHdr>, is there any way to add the bold highlighted info in below?

< GrpHdr>
    ....
    < InitgPty>
        < Nm>...< /Nm>
        **< Id>
            < OrgId>
                < Othr>
                    < Id>VAT< /Id>
                </Othr>
            < /OrgId>
        < /Id>**
    < /InitgPty>
< /GrpHdr>

**Comment by Sin3W** [comment]
No one leave a reply

**Comment by Kidsan** [comment]
Just ran in to this issue also. My bank requires `InitgPty.id.PrvtId.Othr.Id` to be populated. Any solution?

**Comment by Kidsan** [comment]
For anyone else who might come across this: I ended up doing a `String.replace('<InitgPty></InitgPty>', desiredInitgPty)` on the outputted XML

**Comment by kewisch** [comment]
Adding support for this should be fairly easy, I'd very much appreciate a PR. A good place to start looking is at https://github.com/kewisch/sepa.js/blob/b490158ada1475998e6fea627f68edd7c29f8de9/lib/sepa.js#L208

**Comment by lippertto** [comment]
Oops, referenced the wrong ticket. Please ignore.

**Comment by dhrp** [comment]
I believe this is fixed by: https://github.com/kewisch/sepa.js/pull/60

**Comment by kewisch** [comment]
Sounds right, thanks!
