### ISSUE TITLE
error genetaing pacs.XXX.XXXX.XXXX files

### ISSUE THREAD

**Issue by Kissema** [kewisch/sepa.js#36]
error genetaing pacs.XXX.XXXX.XXXX files

**Comment by kewisch** [comment]
I'm not sure what this means. I wrote this for pain transfers mainly, if there is something missing this is likely an enhancement. Given I missed this in 2020 I suspect you might have moved on, but if you are interested in adding support please do create a new issue and I'll take a look at the PR.
