### ISSUE TITLE
`docDeclaration` broken in Chrome

### ISSUE THREAD

**Issue by nicolasschabram** [kewisch/sepa.js#52]
Hi @kewisch

thank you for providing this handy library!

I encountered a small issue when trying to make it work in a browser environment: It seems like the `docDeclaration` string generated in the `toString()` method doesn't work in Chrome. In my current build environment, it produces this:

```xml
<?xml version="1.0" encoding="null"?>
```

I've also reproduced the issue on Codepen: https://codepen.io/nicolasschabram/pen/ExOdybw. In Firefox, it works fine. But in the Chrome browser console, you will receive this error:

```
sepa.js:89 Uncaught TypeError: Cannot set property xmlEncoding of #<Document> which has only a getter
    at SepaDocument.toXML (sepa.js:89:25)
    at SepaDocument.toString (sepa.js:102:24)
    at pen.js?key=pen.js-772711c0-9717-49a1-2466-dddc332647a2:18:17
```

I believe that's because [`xmlEncoding`](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlEncoding) (as well as [`xmlVersion`](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlVersion)) are deprecated and no longer fully supported in some browsers.

I've prepared a proposal for a fix in this PR: #53. Does that make sense to you?

Thanks,
Nicolas

**Comment by coxato** [comment]
I don't know why, but I think I start getting this same error when changed from create-react-app to vite. 

So I had to create a file `sepa-patch.ts` 
```ts
// Patch for sepa library to handle xmlEncoding issue
if (typeof Document !== "undefined") {
  // Create a patched version that ignores xmlEncoding setter
  Object.defineProperty(Document.prototype, "xmlEncoding", {
    get: function () {
      return "UTF-8";
    },
    set: function (value) {
      // Ignore the setter to prevent the error
      console.warn("xmlEncoding is deprecated and read-only, ignoring setter");
    },
    configurable: true,
  });
}

```
then import before the sepa 

```ts
import "./sepa-patch";
import SEPA from "sepa";
```
and now is working good again.
