### ISSUE TITLE
Cannot set property xmlEncoding of `#<Document>`  which has only a getter

### ISSUE THREAD

**Issue by nicolasschabram** [kewisch/sepa.js#56]
Hi @kewisch, thanks for merging and releasing my fix for #52!

As it turns out, it only seems to address half of the problem for us. It worked for a while but after we've switched to a different build setup, we're back to the same error in Chrome:

```
sepa.js:89 Uncaught TypeError: Cannot set property xmlEncoding of #<Document> which has only a getter
    at SepaDocument.toXML (sepa.js:89:25)
    at SepaDocument.toString (sepa.js:102:24)
    at pen.js?key=pen.js-772711c0-9717-49a1-2466-dddc332647a2:18:17
```

Here's a reproduction case with the new version (1.1.0): https://codepen.io/nicolasschabram/pen/QWYgXrW.

Looking at it again, it kinda makes sense that [my previous PR](https://github.com/kewisch/sepa.js/pull/53) didn't completely solve the issue. The fact that it worked for a while for us maybe has something to do with the available polyfills in our application but I didn't fully get to the bottom of it.

Anyway, [`xmlEncoding`](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlEncoding) and [`xmlVersion`](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlVersion) are clearly deprecated and it doesn't seem to me like setting them serves any actual purpose in this library. So I've prepared another MR to remove them completely (like I hinted at in [this earlier comment](https://github.com/kewisch/sepa.js/pull/53/files/b0e5fde63229025f7d960d60311e96495e074f2a#diff-8033935593c13d263d07a95fd467fdd269df7266e669e24e256f39281b9a8908L159)): https://github.com/kewisch/sepa.js/pull/57.

**Comment by kewisch** [comment]
Thanks again for the PR. I'm wondering if we should be using `XMLSerializer` instead, but that might be for a new issue.
