### ISSUE TITLE
Debtor Id does not seem to be mandatory for pain 001

### ISSUE THREAD

**Issue by lippertto** [kewisch/sepa.js#58]
Hello,
I am trying to generate an xml file for a sepa transfer.
I get the message that `debtorId is invalid`, which is true because I do not set a debtor id.
From what I read in the documentation of the pain format, the debtorId is not required for transfer xml files.

If you agree, I would like to submit a patch to remove the check when it is a transfer.

The patch would modify the `validate()` function for `SepaPaymentInfo`
https://github.com/kewisch/sepa.js/blob/f435a97b75df7a929ad9f2c14002009f558e0328/lib/sepa.js#L359

**Comment by dhrp** [comment]
Yes, additionally; what I have found is that the validation fails for (all) Dutch bank IBANs I have tried, the empty string and anything else, except for german iBAN's. It would like to see this be an optional field. -- Additionally; I noticed in the 003 document generated the ID doesn't even show...

**Comment by lippertto** [comment]
Hello @dhrp,

I am working on including the id in both formats (001 and 003)

Just to make sure: did you put IBANs or Creditor Ids into the field? Creditor Ids have a different format from IBANs. There is a German Wikipedia [article](https://de.wikipedia.org/wiki/Gl%C3%A4ubiger-Identifikationsnummer) on this, but I did not see a Dutch one. But maybe Deepl can help you to translate it.

If you put Dutch Creditor Ids into the field and the validation failed, can you give me an example, so that I can reproduce the behavior?

Best, Tobias

**Comment by dhrp** [comment]
Thank you for your message @lippertto. From what I now can find I understand that there is such a thing.. 😀 In NL based on the chamber of commerce number.

However, in what I can find it is only required for a 001 direct debit (draft money from others) file, and not for a payment batch file. Can we make the field optional in a 003 batch payment file? 

Now I know how to calculate my number I can do it, but our banks' website says you find the number on the direct debit contract. Which we don't have and don't need. 

And just to be superfluously clear, we also don't need it for the people we pay to, as these private individuals do not have one.

**Comment by dhrp** [comment]
Ah. Haha. Noticed you already made it optional. Thanks!
