### ISSUE TITLE
Option to do transfers

### ISSUE THREAD

**Issue by CuReSoft** [kewisch/sepa.js#6]
Am i getting it right. At the moment only direct debits are possible?

It would be nice to have the option to do transfers as well.

**Comment by kewisch** [comment]
Yes, I'm pretty sure I only implemented direct debit at the time because that is what I needed. It shouldn't be too hard to add credit transfers though.

**Comment by SeyZ** [comment]
:+1: for transfers :)

**Comment by OtaK** [comment]
Hi,

We are needing SEPA Transfers at my company, so I've went ahead and forked sepa.js at https://github.com/melberries/sepa.js.

I'm currently working on the transfer feature, so I'll keep this issue updated and submit a PR once done and well-tested.

**Comment by kewisch** [comment]
Thank you for working on this! Let me know if you have any questions.

**Comment by OtaK** [comment]
Should we close this issue now?

**Comment by kewisch** [comment]
Sure, lets do it
