### ISSUE TITLE
why do you need to provide a mandat for a money transfer? What is a debtorId? 

### ISSUE THREAD

**Issue by i-wahdan** [kewisch/sepa.js#66]
Hi, I am trying to check the functionality of the library, but I have no idea what kind of information is needed and why.

For example, a mandate in SEPA is only needed for a direct debit, why must it be defined for a money transfer? 
Also why is Mandate Signature Date not an optional field where it is not required from actual banks? 
Also I know what is a creditorId for a direct debit, but no where in the internet is there a reference of such thing as debtorId. What is this supposed to be? 

I hope someone is still there maintaining the library who can check these questions. Thanks!

**Comment by kewisch** [comment]
I'm still maintaining the library, though honestly I never ended up using it in production so I can't answer more specific questions. I went by my understanding of the spec back then. I'm happy to accept changes and would appreciate pointers to the spec when doing so.

**Comment by fellmann** [comment]
To my limited understanding:
- the mandate is only required for direct debit, I have removed the check for transfers
- the debitor id is not required, and incorrectly serialized at the moment.

So, mandate id, mandate signature date and debitor id should not be set for transfer.
