### ISSUE TITLE
Is there any plan to implement pain.008.001.08 / pain.001.001.09 / Version: 3.7

### ISSUE THREAD

**Issue by maasolli** [kewisch/sepa.js#67]
See  

https://www.ebics.de/de/datenformate/ergaenzende-dokumente

and

https://www.bundesbank.de/resource/blob/877540/eec34592d2bf123596897cf29448e04b/mL/technische-spezifikationen-sepa-lastschriften-2023-11-data.pdf

**Comment by kewisch** [comment]
I don't have a need for these pain formats myself, but if someone is interested in patching for these format I'm happy to review!

**Comment by leMaik** [comment]
@kewisch I guess this can be closed now that #68 is merged :tada:
