### ISSUE TITLE
Error: Cannot find module 'sepa'

### ISSUE THREAD

**Issue by SeyZ** [kewisch/sepa.js#7]
Trying to use `sepa.js` on my Nodejs application.
After installing it via `npm install sepa.js --save`, I run `node` and run: `require('sepa')`. The result is:

    > require('sepa')
    Error: Cannot find module 'sepa'

**Comment by kewisch** [comment]
Thats my fault, for poorly choosing the node name. I'll try to rename it on npm, in the meanwhile please use `require('sepa.js')`

**Comment by kewisch** [comment]
Ok, done. http://npmjs.org/package/sepa
I haven't deleted the old package at http://npmjs.org/package/sepa.js but I did put in a deprecation notice. Not sure if thats the best way to go about it, maybe since the user base is small its ok to just remove the old one.

**Comment by kewisch** [comment]
2c0d5af48e918d6df8c1ca7e2fbaf044e89d14fe

**Comment by SeyZ** [comment]
@kewisch Thanks for your reactivity.

In my `package.json` file I have `0.8.2` version. But still have the bug:

`Error: Cannot find module 'sepa'`

**Comment by kewisch** [comment]
Can you show me your package.json? Did you run `npm install --save sepa` ? I've tested this from a fresh new directory and it seems to work for me.
